name: highflyer
channels:
  - defaults
dependencies:
  - python=3.11
  - pip:
      - cvzone==1.6.1
      - opencv-contrib-python==4.9.0.80
      - opencv-python==4.9.0.80
      - pyserial
      - mediapipe
